### ISSUE TITLE
Qt5.15.0 does not work on windows

### ISSUE THREAD

**Issue by LorenzE** [miurahr/aqtinstall#134]
Wit the command
```
python -m aqt install -O D:\a\mne-cpp/Qt 5.15.0 windows desktop win64_msvc2017_64 -m qtcharts
```
I get the the following error message
```
2020-05-27 14:52:30,736 - aqt - INFO - aqtinstall(aqt) v0.8 on Python 3.7.7 [CPython MSC v.1900 64 bit (AMD64)]
2020-05-27 14:52:30,736 - aqt - WARNING - Some of specified modules are unknown.
2020-05-27 14:52:31,878 - aqt - ERROR - Error while parsing package information!
##[error]The process 'python' failed with exit code 1
```

See [here](https://github.com/mne-tools/mne-cpp/pull/632/checks?check_run_id=713474243) for the complete log. The corresponding github workflow script can be found [here](https://github.com/LorenzE/mne-cpp/blob/qt515/.github/workflows/pullrequest.yml). Linux and macos work fine. 

Do you have any ideas what might be happening?

**Comment by miurahr** [comment]
Uhmm, aqtinstall works with Qt 5.15.0 on windos on github hosted  environment.
https://github.com/miurahr/aqtinstall/runs/701956775

This error  indicates there is no matched target package found from Qt download sites XML metadata.
https://github.com/miurahr/aqtinstall/blob/72c4589e7ddfb21e420f5900ad377d61a2ea83c8/aqt/archives.py#L143-L146

aqt v0.8 was tested with 5.14.x,  and aqt v0.9.0b3 is tested with 5.15.0. 
Could you try v0.9.0 beta version?

**Comment by miurahr** [comment]
You can do it with

```
    - name: Install Qt (Windows)
      if: matrix.os == 'windows-2016'
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        arch: win64_msvc2017_64
        modules: qtcharts
        aqtversion: 0.9.0b3 
```

**Comment by LorenzE** [comment]
Got it to work. I just used the wrong architecture parameter. Sorry for the noise.

**Comment by miurahr** [comment]
Great. I'd like to release it as production soon.

**Comment by altendky** [comment]
@LorenzE the arch you listed (`win64_msvc2017_64`) matches what @miurahr suggested.  What did you change it to to fix it?  I'm running into at least something 'similar' but figured I'd see what you changed first.  No need to dig but my log is https://gist.github.com/altendky/e089eefd97ad11d86cde62515a96942a and the command line is shown on the lines before the error.

**Comment by LorenzE** [comment]
@altendky I got it to work with `win64_msvc2019_64`. Qt ditched MSVC 2017 pre-builts for 5.15:

``` 
  - name: Install Qt 5.15.0 (Windows)
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.0
        arch: win64_msvc2019_64
        modules: qtcharts
```

Just fyi: I did some testing and was able to build `win64_msvc2019_64` arch on the `windows-2017` runner with MSVC2017 installed (instead of MSVC 2019 which is available in the `windows-2019` runner). I assume this is because of [MSVC compability between versions](https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019).

Hope this helps.
