### ISSUE TITLE
Add WinGet installation to ReadMe

### ISSUE THREAD

**Issue by russellbanks** [miurahr/aqtinstall#625]
aqtinstall is now available from WinGet under `winget install aqtinstall`, added in https://github.com/microsoft/winget-pkgs/pull/90217. This uses the `aqt_x64.exe` and `aqt_x86.exe` portable exe's and sets up all the links so that it can be used as if it were installed from pip, allowing the user to just run `aqt`. If you wish, this can be added to the ReadMe as an alternative option, especially as this means that users don't have to either have Python installed or worry about which version of Python to have installed.

Future releases to WinGet can also be automated with [WinGet Releaser](https://github.com/vedantmgoyal2009/winget-releaser), if this is something you would be interested in. It's a workflow that runs on release and would look a little bit like this:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v1
        with:
          identifier: miurahr.aqtinstall
          installers-regex: 'aqt_[A-Za-z0-9]+\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
```
