### ISSUE TITLE
No RCC command on linux with Qt 6.5.2

### ISSUE THREAD

**Issue by tamlok** [miurahr/aqtinstall#717]
Hi,

I install Qt 6.5.2 in CI:

```
- name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.2
          target: desktop
          modules: 'qtwebengine qtwebchannel qtpositioning qtpdf qtimageformats qt5compat'
          cache: 'true'
```

But got error:

```
make[1]: Entering directory '/home/runner/work/vnote/build/src'
/home/runner/work/vnote/Qt/6.5.2/gcc_64/bin/rcc -name extra -binary ../../vnote/src/data/extra/extra.qrc -o vnote_extra.rcc
make[1]: /home/runner/work/vnote/Qt/6.5.2/gcc_64/bin/rcc: Command not found
make[1]: *** [Makefile:2076: vnote_extra.rcc] Error 127
make[1]: Leaving directory '/home/runner/work/vnote/build/src'
make: *** [Makefile:74: sub-src-make_first] Error 2
```

A tree of the Qt bin dir:

```
Run qmake -v
QMake version 3.1
Using Qt version 6.5.2 in /home/runner/work/vnote/Qt/6.5.2/gcc_64/lib
/home/runner/work/vnote/Qt
└── 6.5.2
    └── gcc_64
        ├── bin
        │   ├── androiddeployqt
        │   ├── androiddeployqt6
        │   ├── androidtestrunner
        │   ├── assistant
        │   ├── designer
        │   ├── lconvert
        │   ├── linguist
        │   ├── lrelease
        │   ├── lupdate
        │   ├── pixeltool
        │   ├── qdbus
        │   ├── qdbuscpp2xml
        │   ├── qdbusviewer
        │   ├── qdbusxml2cpp
        │   ├── qdistancefieldgenerator
        │   ├── qdoc
        │   ├── qmake
        │   ├── qmake6
        │   ├── qml
        │   ├── qmldom
        │   ├── qmleasing
        │   ├── qmlformat
        │   ├── qmllint
        │   ├── qmlls
        │   ├── qmlplugindump
        │   ├── qmlpreview
        │   ├── qmlprofiler
        │   ├── qmlscene
        │   ├── qmltc
        │   ├── qmltestrunner
        │   ├── qmltime
        │   ├── qt-cmake
        │   ├── qt-configure-module
        │   ├── qt.conf
        │   ├── qtdiag
        │   ├── qtdiag6
        │   ├── qtpaths
        │   ├── qtpaths6
        │   └── qtplugininfo
        ├── doc
```

Thanks!
