### ISSUE TITLE
IFW is outdated 

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#792]
### Bug description

At now Qt release ifw 4.8, but aqt known about 4.7 only. 

### Expected behavior

The latest version of ifw should be available to download. 

### aqt and python version

INFO    : aqtinstall(aqt) v3.1.15 on Python 3.10.12 [CPython GCC 11.4.0]

### Operating System

Linux/Unix

### Relevant log output

```shell
INFO    : aqtinstall(aqt) v3.1.15 on Python 3.10.12 [CPython GCC 11.4.0]
WARNING : Specified target combination "linux tools_ifw qt.tools.ifw.48" did not exist when this version of aqtinstall was released. This may not install properly, but we will try our best.
ERROR   : The package 'qt.tools.ifw.48' was not found while parsing XML of package information!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pzhlkj6612** [comment]
I can confirm that QIFW 4.8 has been released: [Qt Online Installer and Qt Installer Framework 4.8.0 Released](https://www.qt.io/blog/qt-online-installer-and-qt-installer-framework-4.8.0-released). However, the https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/ directory does not contain 4.8; while https://download.qt.io/online/qtsdkrepository/linux_x64/ifw/ contains both 4.7 and 4.8. I guess that aqtinstall doesn't know the latter path.

```diff
- https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_ifw/
+ https://download.qt.io/online/qtsdkrepository/linux_x64/ifw/

```

.

**Comment by franke-biosaxs** [comment]
Came here for the same.

**Comment by pzhlkj6612** [comment]
It seems that Qt has updated the IFW path of almost all architectures:

- https://download.qt.io/online/qtsdkrepository/windows_x86/ifw/
- https://download.qt.io/online/qtsdkrepository/mac_x64/ifw/
- https://download.qt.io/online/qtsdkrepository/linux_x64/ifw/
- https://download.qt.io/online/qtsdkrepository/linux_arm64/ifw/

.

**Comment by EndrII** [comment]
@miurahr do you have any plans (and free time of course) about fix this issue ?

**Comment by miurahr** [comment]
As usual, you are welcome to give us a PR to update URL path of the code.

**Comment by miurahr** [comment]
We may need to update here when IFW, don't use `self.target` to construct URL path;
https://github.com/miurahr/aqtinstall/blob/b789314264ceb3d2e656d363939a42a952a79ccd/aqt/archives.py#L409-L421

**Comment by Kidev** [comment]
I'm convinced the Qt team has quarterly meetings to discuss how they can change the online repos structure 🧑‍🔧

**Comment by Kidev** [comment]
In a serious note, with the latest changes to `aqtinstall`, you _**should**_ be able to have an easy fix available immedialty for those cases. Use the feature `--use-official-installer [email] [pw]` without changing anything else. It'll usually work because when they change the repo structure, they change the logic of their installer. You may just sometimes need to adjust the name of the `modules`

**Comment by Kidev** [comment]
I'm working [on a PR](https://github.com/Kidev/aqtinstall/pull/23) to fix that but its scope is wider. This is an issue that's going to keep happening and it would be nice if we could distribute a path map to fix issues without having to push releases.

Note my PR enables the installation of the latest versions of IFW, **it works**, but it is going to be updated quite a lot. So if you intend to use it as is (if you are in a hurry), make sure you target a specific commit hash as I don't guarantee all the commits I'll push to that PR will be working

```console
kidev:~$ python -m aqt list-tool windows desktop tools_ifw
qt.tools.ifw.49
qt.tools.ifw.48
qt.tools.ifw.47
kidev:~$ python -m aqt list-tool windows_arm64 desktop tools_ifw
qt.tools.ifw.49
qt.tools.ifw.48
kidev:~$ python -m aqt install-tool windows desktop ifw                                  
INFO    : aqtinstall(aqt) v0.1.dev1935 on Python 3.12.9 [CPython GCC 14.2.1 20250207]
INFO    : Downloading qt.tools.ifw.49...
INFO    : Redirected: mirrors.20i.com
```

**Comment by Kidev** [comment]
You can @kwagyeman, you can use the the param `aqtsource`:

```yml
aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@a833b2c2b99ea02a6f565210c50a1f711c032975'
```

**Comment by kwagyeman** [comment]
Question, I'm specifing my install like so:

```
- name: '⬇ Install Qt on Windows'
      if: matrix.map.host == 'windows' || matrix.map.host == 'windows-factory'
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: 'C:\Users\runneradmin'
        modules: 'qtimageformats qtserialport qt5compat'
        cache: true
        tools: 'tools_cmake tools_ifw tools_ninja tools_mingw90'
```

Which pulls 4.7. So, if I just do:

```
- name: '⬇ Install Qt on Windows'
      if: matrix.map.host == 'windows' || matrix.map.host == 'windows-factory'
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.1'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        dir: 'C:\Users\runneradmin'
        modules: 'qtimageformats qtserialport qt5compat'
        cache: true
        tools: 'tools_cmake tools_ifw tools_ninja tools_mingw90'
        aqtsource: 'git+https://github.com/Kidev/aqtinstall.git@a833b2c2b99ea02a6f565210c50a1f711c032975'
```

I'm good?
