### ISSUE TITLE
modules `qtcharts` not installed when version is 5.9

### ISSUE THREAD

**Issue by hellodword** [miurahr/aqtinstall#81]
```yaml
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.2.1
        with:
          modules: qtcharts
          version: 5.9
```

`qtcharts` will not been installed

I can only find the module download link and fetch it with curl😂:

```sh
curl -o qtcharts.7z -L  https://download.qt.io/online/qtsdkrepository/mac_x64/desktop/qt5_59/qt.59.qtcharts.clang_64/5.9.0-0-201705291821qtcharts-MacOS-OSX_10_10-Clang-MacOS-OSX_10_10-X86_64.7z
 
7za x qtcharts.7z
```
